import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd
import warnings
from ecomm_review_analyzer.errors import ColumnNameNotStringError, ColumnNameNotExistError, ColumnNameEmptyError, \
    DataFrameEmptyError

warnings.filterwarnings('ignore')

class DataVisualizer:
    def __init__(self, df):
        if df.empty:
            raise DataFrameEmptyError()

        self.df = df
        # configure the graphic style
        sns.set_theme(style="white")
        sns.set_palette("mako")
        sns.despine()

    def _validate_data(self, column_name: str) -> str:
        """
        Validates and sanitizes the provided column name.

        This method performs a series of checks:
            1. Verifies that the input is a string.
            2. Removes leading and trailing whitespaces.
            3. Ensures the column name is not empty.
            4. Confirms that the column exists in the DataFrame.

        Args:
            column_name (str): The name of the column to validate.

        Returns:
            str: The cleaned and validated column name.

        Raises:
            ColumnNameNotStringError: If column_name is not a string instance.
            ColumnNameEmptyError: If column_name is empty or contains only spaces.
            ColumnNameNotExistError: If column_name is not found in the DataFrame's columns.
        """

        # validate if the column_name is a string or not (Type check)
        # if the column_name is None, it will be captured here
        if not isinstance(column_name, str):
            raise ColumnNameNotStringError()

        # remove the extra space at the beginning and at the end
        column_name = column_name.strip()

        # check if the column_name is empty or only includes spaces
        # if column_name is " ", not column_name will become True. Please note that it´s not "if column_name is None"
        if not column_name:
            raise ColumnNameEmptyError()

        # check if the column_name exists in the dataframe
        # as the column_name needs to be case-sensitive in this case, hence will not change to .lower()
        if column_name not in self.df.columns:
            raise ColumnNameNotExistError(column_name)

        return column_name

    @staticmethod
    def _setup_canvas(ax, figsize=(12, 6), **kwargs):
        """
        Helper: Handles logic to create a new figure or use an existing axes.
        Returns: fig, ax, own_fig (boolean indicating if we created the figure)
        """

        # fig is like a table, and the ax is like the dishes on it,
        # we can have more than one dish on the same table
        # separate this method because it´s been repeated several times in the whole plotting process
        if ax is None:
            fig, ax = plt.subplots(figsize=figsize, **kwargs)
            own_fig = True
        else:
            fig = ax.get_figure()
            own_fig = False
        return fig, ax, own_fig

    @staticmethod
    def _finalize_canvas(fig, ax, own_fig):
        """
        Helper: Handles the logic of closing the figure to avoid duplicates in Jupyter.
        """
        # if we don´t close the fig before return fig, the Jupiter book will show two identical chart
        # the first chart is generated by matplotlib when we use plt.subplots()
        # the second chart is generated by Jupiter when it seems the return fig
        if own_fig:
            plt.close(fig)
            return fig
        return ax

    def plot_histogram(self, column_name: str="Age", ax=None, **kwargs):
        """"
        Plots a histogram with a Kernel Density Estimate (KDE) for a numerical column.

        This method visualizes the distribution of a specific column. It automatically
        rotates the x-axis labels if the column contains categorical data (strings).

        Args:
            column_name (str, optional): The name of the column to plot. Defaults to "Age".
            ax (matplotlib.axes.Axes, optional): Pre-existing axes for the plot.
                If None, a new figure and axes are created. Defaults to None.
            **kwargs: Additional keyword arguments passed to `sns.histplot`.

        Returns:
            matplotlib.figure.Figure or matplotlib.axes.Axes: The generated figure object
            (if a new figure was created) or the axes object (if `ax` was provided).
            Returns None if an error occurs.
        """
        try:
            column_name=self._validate_data(column_name)

            fig, ax, own_fig = self._setup_canvas(ax, figsize =(12, 6))

            sns.histplot(
                data=self.df,
                x=column_name,
                discrete=True,
                kde=True,
                ax=ax,
                **kwargs # allow extra parameters to sns.histplot
            )

            ax.set_title(f"{column_name} Distribution")
            ax.set_xlabel(column_name)
            ax.set_ylabel("Frequency")

            # rotate the column name 45 grades, when it´s a string
            if self.df[column_name].dtype == 'object':
                ax.tick_params(axis='x', rotation=45)

            return self._finalize_canvas(fig, ax, own_fig)

        except Exception as error:
            print(error)
            plt.close()
            return None


    def _get_category_order(self, column_name: str, sort_by_index: bool):
        """
        Determines the display order for categorical labels in a plot.

        This helper method calculates how categories should be arranged on a chart axis,
        offering a choice between alphanumeric sorting or frequency-based sorting.

        Args:
            column_name (str): The name of the categorical column to analyze.
            sort_by_index (bool): If True, categories are sorted by their label (e.g., A-Z or 1-10).
                If False, categories are sorted by their frequency of occurrence (highest to lowest).

        Returns:
            pandas.Index or list: A sequence of unique category values in the specified order,
            intended to be passed to the 'order' parameter in Seaborn plotting functions.
        """
        if sort_by_index:
            return sorted(self.df[column_name].unique())
        else:
            return self.df[column_name].value_counts().sort_values(ascending=False).index

    def plot_bar_chart(self, column_name: str="Division Name", orientation: str="h", sort_by_index: bool =False, ax=None, **kwargs):
        """"
        Plots a bar chart (countplot) for a categorical column.

        Visualizes the frequency of categories within a column. Supports vertical or
        horizontal orientation and flexible sorting options.

        Args:
            column_name (str, optional): The name of the categorical column. Defaults to "Division Name".
            orientation (str, optional): The orientation of the bars. 'v' for vertical,
                'h' for horizontal. Defaults to "h".
            sort_by_index (bool, optional): If True, sorts bars by category label (alphabetical/numerical).
                If False, sorts bars by frequency (descending). Defaults to False.
            ax (matplotlib.axes.Axes, optional): Pre-existing axes for the plot. Defaults to None.
            **kwargs: Additional keyword arguments passed to `sns.countplot`.

        Returns:
            matplotlib.figure.Figure or matplotlib.axes.Axes: The figure or axes object containing the plot.
            Returns None if an error occurs.
        """
        try:
            column_name = self._validate_data(column_name)

            order = self._get_category_order(column_name, sort_by_index)

            fig, ax, own_fig = self._setup_canvas(ax, figsize=(10, 5))

            # as this part needs to be used twice, better to use one variable plot_params
            plot_params = {
                "data": self.df,
                "order" : order,
                "palette": "mako",
                "ax": ax,
                **kwargs  # allow extra parameters to sns.barplot
            }

            if orientation == "v":
                # x='column_name', use x when we need a vertical bar chart, use y when we need a horizontal bar chart
                sns.countplot(x=column_name, **plot_params)
                ax.set_xlabel(column_name)
                ax.set_ylabel("Frequency")

            else:
                sns.countplot(y=column_name, **plot_params)
                ax.set_ylabel(column_name)
                ax.set_xlabel("Frequency")

            ax.set_title(f"Absolute counts: {column_name}")

            return self._finalize_canvas(fig, ax, own_fig)

        except Exception as error:
            print(error)
            plt.close()
            return None

    def _prepare_pie_data(self, column_name: str, labels: list):
        """
        Prepares frequency data and labels for pie chart visualization.

        This internal helper aggregates the unique values in a categorical column,
        sorts them by their index (to ensure consistent ordering), and handles
        default label assignment if custom labels are not provided.

        Args:
            column_name (str): The name of the categorical column to process.
            labels (list, optional): A list of custom labels for the pie slices.
                If None, the unique values from the column index are used as labels.

        Returns:
            tuple: A tuple containing (data, labels, n_counts):
                - data (numpy.ndarray): The frequency counts for each category.
                - labels (pandas.Index or list): The names of the categories.
                - n_counts (int): The total number of unique categories (used for color palettes).
        """

        counts = self.df[column_name].value_counts().sort_index()
        data = counts.values

        if labels is None:
            labels = counts.index
        return data, labels, len(counts)

    def plot_general_pie_chart(self, column_name: str="Rating", title: str=None, labels: list=None, ax=None, size: tuple =(5, 5)):
        """
        Plots a generic pie chart for any categorical column.
        This method automatically generates a color palette based on the number of unique
        values in the column and displays percentages.

        Args:
            column_name (str, optional): The name of the column to visualize. Defaults to "Rating".
            title (str, optional): The title of the chart. If None, generates a default title.
            labels (list, optional): Custom labels for the pie slices. If None, uses the column's unique values.
            ax (matplotlib.axes.Axes, optional): Pre-existing axes for the plot. Defaults to None.
            size (tuple, optional): The size of the figure (width, height). Defaults to (5, 5).

        Returns:
            matplotlib.figure.Figure: The generated figure object. Returns None if an error occurs.

        """
        try:
            column_name = self._validate_data(column_name)

            data, labels, n_counts = self._prepare_pie_data(column_name, labels)

            fig, ax, own_fig = self._setup_canvas(ax, figsize=size)

            colors = sns.color_palette("mako", n_colors=n_counts) # another option os palette es Blues_r
            final_title = title if title else f"Distribution of {column_name}"

            ax.pie(
                data, # don´t put data=data, don´t confuse with seaborn, matplotlib don´t need to put data=xx.
                labels=labels,
                colors=colors,
                autopct="%1.1f%%",
                startangle=90,
                wedgeprops={'edgecolor': 'white', 'linewidth': 1.5}
            )

            # use ax.set_title instead of plt.title
            ax.set_title(final_title, fontsize=14, pad=20)

            if own_fig:
                fig.tight_layout()

            # to avoid that Jupiter book show again the same chart
            return self._finalize_canvas(fig, ax, own_fig)

        except Exception as error:
            print(error)
            return None

    def _calculate_crosstab(self, row_col: str, col_col: str, normalize: bool):
        """
        Calculates a contingency table (crosstab) between two categorical variables.

        This internal helper generates the data matrix required for heatmaps. It can
        either count the occurrences of category pairs or calculate their percentage
        relative to the entire dataset.

        Args:
            row_col (str): The name of the column to be used for the table rows (index).
            col_col (str): The name of the column to be used for the table columns.
            normalize (bool): If True, the method calculates percentages relative to the
                total number of samples, multiplied by 100 and rounded. If False, it
                returns absolute frequency counts.

        Returns:
            pd.DataFrame: A cross-tabulated DataFrame where rows represent categories of
            'row_col' and columns represent categories of 'col_col'.
        """
        if normalize:
            # normalize= True: the sum of the percentage of the whole chart is 100%
            # normalize="index": the sum of each row is 100%
            # normalize="columns": the sum of each column is 100%
            return pd.crosstab(
                index=self.df[row_col],
                columns=self.df[col_col],
                normalize=True
            ).mul(100).round(0)

        else:
            # pd.crosstab generate a pandas dataframe
            return pd.crosstab(index=self.df[row_col], columns=self.df[col_col])

    def plot_one_heatmap(self, row_col: str ="Division Name", col_col: str ="Department Name", normalize: bool =False, ax=None, cmap=None, **kwargs):
        """
        Plots a single heatmap showing the relationship between two categorical columns.
        Can display either absolute counts (frequency) or normalized percentages.

        Args:
            row_col (str, optional): The column name for the heatmap rows. Defaults to "Division Name".
            col_col (str, optional): The column name for the heatmap columns. Defaults to "Department Name".
            normalize (bool, optional): If True, displays percentages summing to 100%.
                If False, displays absolute counts. Defaults to False.
            ax (matplotlib.axes.Axes, optional): Pre-existing axes for the plot. Defaults to None.
            cmap (str, optional): The colormap to use. Defaults to "Blues" (counts) or "Greens" (percentages).
            **kwargs: Additional keyword arguments passed to `sns.heatmap`.

        Returns:
            matplotlib.figure.Figure or matplotlib.axes.Axes: The figure or axes object.
            Returns None if an error occurs.
        """
        try:
            row_col = self._validate_data(row_col)
            col_col = self._validate_data(col_col)

            fig, ax, own_fig = self._setup_canvas(ax, figsize=(8, 4))

            table = self._calculate_crosstab(row_col, col_col, normalize)

            # fmt='g' means general, which can adapt to different case; fmt="d": int
            fmt = '.1f' if normalize else 'g'
            default_cmp = "Greens" if normalize else "Blues"
            label = "Percentage %" if normalize else "Count"
            title = f"Percentage Distribution: {row_col} vs {col_col}" if normalize else f"Absolute Count: {row_col} vs {col_col}"

            sns.heatmap(
                data=table, # as Pandas DataFrame is provided, the index/column information will be used to label the columns and rows.
                annot=True, # show the number on the chart or not
                ax=ax,
                fmt=fmt,
                cmap=cmap or default_cmp,
                linewidths=0.5,
                cbar_kws={"label": label},
                **kwargs
            )

            ax.set_title(title, fontsize=12)

            # fig.tight_layout() or plt.tight_layout()
            # which allow us to adjust automatically the space between ax[0] and ax[1] to avoid overlapping
            if own_fig:
                fig.tight_layout()

            return self._finalize_canvas(fig, ax, own_fig)

        except Exception as error:
            print(error)
            return None

    def plot_heatmap_comparison(self, row_col: str ="Division Name", col_col: str ="Department Name"):
        """
        Plots two heatmaps side-by-side for comparison: Absolute Counts vs. Percentages.

        This method is a wrapper that calls `plot_one_heatmap` twice to generate a
        composite figure.

        Args:
            row_col (str, optional): The column name for the heatmap rows. Defaults to "Division Name".
            col_col (str, optional): The column name for the heatmap columns. Defaults to "Department Name".

        Returns:
            matplotlib.figure.Figure: The generated figure containing the side-by-side subplots.
        """
        fig, ax = plt.subplots(1, 2, figsize=(16, 4))
        self.plot_one_heatmap(row_col, col_col, ax=ax[0])
        self.plot_one_heatmap(row_col, col_col, ax=ax[1], normalize=True)

        fig.tight_layout()
        plt.close(fig)
        return fig

    def _calculate_recommendation_matrix(self, row_col: str, col_col: str, values_col: str, min_samples: int):
        """
        Helper: Calculates the pivot table with recommendation rates.
        Applies a threshold mask to filter out statistically insignificant data.
        """
        count_table = self.df.pivot_table(
            index=row_col,
            columns=col_col,
            values=values_col,
            aggfunc="count"
        )

        rate_table = self.df.pivot_table(
            index=row_col,
            columns=col_col,
            values=values_col,
            aggfunc="mean"
        ).mul(100).round(0)

        # discharge if one category has less than min_samples, for example, 5
        return rate_table.where(count_table >= min_samples)

    def plot_recommendation_rate_heatmap(self, row_col: str = "Age Group", col_col: str="Department Name", values_col: str="Recommended IND", min_samples: int=5, ax=None, **kwargs):
        """
        Plots a heatmap of the average recommendation rate (pivot table).

        Calculates the mean of `values_col` (e.g., 'Recommended IND') grouped by
        `row_col` and `col_col`. Cells with fewer samples than `min_samples` are masked.

        Args:
            row_col (str, optional): The grouping column for rows. Defaults to "Age Group".
            col_col (str, optional): The grouping column for columns. Defaults to "Department Name".
            values_col (str, optional): The numerical column to average (usually 0/1). Defaults to "Recommended IND".
            min_samples (int, optional): The minimum sample count required to show a cell. Defaults to 5.
            ax (matplotlib.axes.Axes, optional): Pre-existing axes for the plot. Defaults to None.
            **kwargs: Additional keyword arguments passed to `sns.heatmap`.

        Returns:
            matplotlib.figure.Figure or matplotlib.axes.Axes: The figure or axes object.
            Returns None if an error occurs.
        """
        try:
            row_col = self._validate_data(row_col)
            col_col = self._validate_data(col_col)
            values_col = self._validate_data(values_col)

            fig, ax, own_fig = self._setup_canvas(ax, figsize=(9, 5))

            table = self._calculate_recommendation_matrix(row_col, col_col, values_col, min_samples)

            sns.heatmap(
                data=table,
                # as Pandas DataFrame is provided, the index/column information will be used to label the columns and rows.
                annot=True,  # show the number on the chart or not
                ax=ax,
                fmt="g",
                cmap="mako",
                linewidths=0.5,
                cbar_kws={"label": "Recommendation Rate (%)"},
                **kwargs
            )

            ax.set_title(f"Recommendation Rate by {row_col} & {col_col}", fontsize=12)

            if own_fig:
                # fig.tight_layout() or plt.tight_layout(),
                # which allow us to adjust automatically the space between ax[0] and ax[1] to avoid overlapping
                fig.tight_layout()

            return self._finalize_canvas(fig, ax, own_fig)

        except Exception as error:
            print(error)
            return None

    def _get_correlation_matrix(self, cols=None):
        """
        Calculates the correlation matrix for a subset of numerical columns.

        This internal helper manages the selection and validation of columns for
        statistical analysis. If no columns are specified, it automatically
        identifies all numerical features in the dataset.
        If a list is provided, it validates each column's existence and ensures
        only numerical data types are included in the final calculation.

        Args:
            cols (list, optional): A list of column names to analyze.
                If None, the method automatically detects all columns with
                numerical data types (int, float).

        Returns:
            pd.DataFrame: A Pearson correlation matrix for the valid numerical columns.
            None: If the resulting subset of columns is empty or contains no
                numerical data.
        """
        if cols is None:
            # when it´s None, the method will use all the columns with numerical data types
            valid_cols = self.df.select_dtypes(include=[np.number]).columns.tolist()
        else:
            temp_cols = []
            for col in cols:
                try:
                    # validate if the column name is valid
                    temp_cols.append(self._validate_data(col))
                except Exception:
                    continue
            # only include the column name when the data type is numerical
            valid_cols = self.df[temp_cols].select_dtypes(include=[np.number]).columns.tolist()

        if len(valid_cols) == 0:
            return None

        # generate the correlation matrix
        return self.df[valid_cols].corr()


    def plot_correlation_heatmap(self, cols=None, ax=None, **kwargs):
        """
        Plots a correlation matrix heatmap for numerical variables.

        Visualizes the Pearson correlation coefficients between selected numerical columns.

        Args:
            cols (list, optional): A list of column names to include in the correlation matrix.
            ax (matplotlib.axes.Axes, optional): Pre-existing axes for the plot. Defaults to None.
            **kwargs: Additional keyword arguments passed to `sns.heatmap`.

        Returns:
            matplotlib.figure.Figure: The generated figure object. Returns None if an error occurs.
        """
        try:
            corr_matrix = self._get_correlation_matrix(cols)

            fig, ax, own_fig = self._setup_canvas(ax, figsize=(10, 8))

            sns.heatmap(
                corr_matrix,
                annot=True,
                fmt='.1f',
                cmap="mako",
                vmin=-1, vmax=1,
                center=0,
                linewidths=0.5,
                cbar_kws={"label": "Correlation"},
                ax=ax,
                **kwargs
            )

            ax.set_title("Numerical Feature Correlation Analysis", fontsize=15, pad=20)

            if own_fig:
                fig.tight_layout()

            # to avoid that Jupiter book show again the same chart
            return self._finalize_canvas(fig, ax, own_fig)

        except Exception as error:
            print(error)
            return None




